# Generated by Django 5.0.1 on 2025-12-04 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('metadata_json', models.JSONField(blank=True, default=dict, help_text='Información adicional sobre la lectura', verbose_name='Metadata JSON')),
                ('mqtt_message_id', models.CharField(blank=True, help_text='Identificador del mensaje MQTT que generó esta lectura', max_length=100, null=True, verbose_name='ID Mensaje MQTT')),
                ('mqtt_qos', models.IntegerField(blank=True, choices=[(0, 'At most once (0)'), (1, 'At least once (1)'), (2, 'Exactly once (2)')], help_text='Quality of Service del mensaje MQTT', null=True, verbose_name='QoS MQTT')),
                ('mqtt_retained', models.BooleanField(default=False, help_text='Indica si el mensaje MQTT fue retenido en el broker', verbose_name='Mensaje Retenido')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='devices.dispositivo', verbose_name='Dispositivo')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='sensors.sensor', verbose_name='Sensor')),
            ],
            options={
                'verbose_name': 'Lectura',
                'verbose_name_plural': 'Lecturas',
                'db_table': 'lecturas',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='idx_lectura_timestamp'), models.Index(fields=['dispositivo', '-timestamp'], name='idx_lectura_disp_ts'), models.Index(fields=['sensor', '-timestamp'], name='idx_lectura_sensor_ts'), models.Index(fields=['mqtt_message_id'], name='idx_lectura_mqtt_msg')],
            },
        ),
    ]
