# Generated by Django 5.0.1 on 2025-12-04 20:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('temperatura', 'Temperatura'), ('humedad', 'Humedad'), ('presion', 'Presión'), ('luz', 'Luz'), ('movimiento', 'Movimiento'), ('gas', 'Gas'), ('sonido', 'Sonido'), ('distancia', 'Distancia'), ('acelerometro', 'Acelerómetro'), ('giroscopio', 'Giroscopio'), ('otro', 'Otro')], db_index=True, max_length=20, verbose_name='Tipo de Sensor')),
                ('unidad_medida', models.CharField(max_length=50, verbose_name='Unidad de Medida')),
                ('rango_min', models.FloatField(validators=[django.core.validators.MinValueValidator(-1000000)], verbose_name='Rango Mínimo')),
                ('rango_max', models.FloatField(validators=[django.core.validators.MaxValueValidator(1000000)], verbose_name='Rango Máximo')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'Mantenimiento')], db_index=True, default='activo', max_length=20, verbose_name='Estado')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('mqtt_topic_suffix', models.CharField(blank=True, help_text='Ejemplo: temperature, humidity. Se usará en el topic MQTT.', max_length=100, null=True, verbose_name='Sufijo de Topic MQTT')),
                ('publish_interval', models.IntegerField(blank=True, help_text='Intervalo recomendado para publicar lecturas de este sensor', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(86400)], verbose_name='Intervalo de Publicación (segundos)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensores_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
                'db_table': 'sensores',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tipo'], name='idx_sensor_tipo'), models.Index(fields=['estado'], name='idx_sensor_estado'), models.Index(fields=['created_by'], name='idx_sensor_created_by'), models.Index(fields=['-created_at'], name='idx_sensor_created_at')],
            },
        ),
    ]
