# Generated by Django 5.0.1 on 2025-12-06 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username o "anonymous" para usuarios no autenticados', max_length=150, verbose_name='Nombre de Usuario')),
                ('module', models.CharField(choices=[('auth', 'Autenticación'), ('users', 'Usuarios'), ('roles', 'Roles'), ('permissions', 'Permisos'), ('devices', 'Dispositivos'), ('sensors', 'Sensores'), ('readings', 'Lecturas'), ('mqtt', 'MQTT'), ('emqx', 'EMQX'), ('admin', 'Administración'), ('api_docs', 'Documentación API'), ('other', 'Otro')], db_index=True, help_text='Módulo o sección accedida', max_length=20, verbose_name='Módulo')),
                ('endpoint', models.CharField(db_index=True, help_text='URL del endpoint accedido', max_length=255, verbose_name='Endpoint')),
                ('method', models.CharField(help_text='GET, POST, PUT, PATCH, DELETE', max_length=10, verbose_name='Método HTTP')),
                ('status_code', models.IntegerField(db_index=True, help_text='Código HTTP de respuesta (200, 404, 500, etc.)', verbose_name='Código de Estado')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Tiempo que tardó la petición en milisegundos', null=True, verbose_name='Tiempo de Respuesta (ms)')),
                ('query_params', models.JSONField(blank=True, default=dict, help_text='Query parameters de la petición', verbose_name='Parámetros de Query')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional sobre el acceso', verbose_name='Metadata')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y Hora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'verbose_name_plural': 'Registros de Acceso',
                'db_table': 'access_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='idx_access_timestamp'), models.Index(fields=['user', '-timestamp'], name='idx_access_user_ts'), models.Index(fields=['module', '-timestamp'], name='idx_access_module_ts'), models.Index(fields=['status_code', '-timestamp'], name='idx_access_status_ts'), models.Index(fields=['ip_address', '-timestamp'], name='idx_access_ip_ts'), models.Index(fields=['endpoint'], name='idx_access_endpoint')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Guardado por si el usuario es eliminado', max_length=150, verbose_name='Nombre de Usuario')),
                ('model_name', models.CharField(db_index=True, help_text='Nombre del modelo afectado (ej: Dispositivo, Sensor)', max_length=100, verbose_name='Modelo')),
                ('object_id', models.IntegerField(db_index=True, help_text='ID del registro afectado', verbose_name='ID del Objeto')),
                ('object_repr', models.CharField(help_text='String representation del objeto', max_length=200, verbose_name='Representación del Objeto')),
                ('action', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar')], db_index=True, max_length=10, verbose_name='Acción')),
                ('changes', models.JSONField(default=dict, help_text='Diccionario con los cambios realizados (antes/después)', verbose_name='Cambios')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP desde donde se realizó la acción', null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, help_text='Información del navegador/cliente', verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y Hora')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='idx_audit_timestamp'), models.Index(fields=['model_name', '-timestamp'], name='idx_audit_model_ts'), models.Index(fields=['user', '-timestamp'], name='idx_audit_user_ts'), models.Index(fields=['action', '-timestamp'], name='idx_audit_action_ts'), models.Index(fields=['model_name', 'object_id'], name='idx_audit_model_obj')],
            },
        ),
    ]
