# Generated by Django 5.0.1 on 2025-12-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accesslog_auditlog'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_chat_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID de chat de Telegram para notificaciones', max_length=50, null=True, unique=True, verbose_name='Telegram Chat ID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_notifications_enabled',
            field=models.BooleanField(default=False, help_text='Recibir notificaciones via Telegram', verbose_name='Notificaciones Telegram Habilitadas'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Username de Telegram (@username)', max_length=100, null=True, verbose_name='Usuario de Telegram'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_verification_code',
            field=models.CharField(blank=True, help_text='Código temporal para verificar cuenta', max_length=10, null=True, verbose_name='Código de Verificación Telegram'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_verification_expires',
            field=models.DateTimeField(blank=True, help_text='Fecha de expiración del código de verificación', null=True, verbose_name='Expiración de Verificación'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_verified',
            field=models.BooleanField(default=False, help_text='Indica si el usuario verificó su cuenta de Telegram', verbose_name='Telegram Verificado'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['telegram_chat_id'], name='idx_user_telegram_chat'),
        ),
    ]
