# Generated by Django 5.0.1 on 2025-12-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Recibir notificaciones via correo electrónico', verbose_name='Notificaciones Email Habilitadas'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, help_text='Última vez que se envió email de verificación', null=True, verbose_name='Fecha de Envío de Verificación'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verification_token',
            field=models.CharField(blank=True, help_text='Token para verificar correo electrónico', max_length=100, null=True, unique=True, verbose_name='Token de Verificación Email'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Indica si el usuario verificó su correo electrónico', verbose_name='Email Verificado'),
        ),
    ]
