# Generated by Django 5.0.1 on 2025-12-04 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('raspberry_pi', 'Raspberry Pi'), ('esp32', 'ESP32'), ('arduino', 'Arduino'), ('esp8266', 'ESP8266'), ('stm32', 'STM32'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de Dispositivo')),
                ('identificador_unico', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Identificador Único')),
                ('ubicacion', models.CharField(max_length=300, verbose_name='Ubicación')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'Mantenimiento'), ('desconectado', 'Desconectado')], db_index=True, default='inactivo', max_length=20, verbose_name='Estado')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('mqtt_enabled', models.BooleanField(db_index=True, default=False, help_text='Indica si el dispositivo tiene MQTT habilitado', verbose_name='MQTT Habilitado')),
                ('mqtt_client_id', models.CharField(blank=True, db_index=True, help_text='Identificador único del cliente MQTT', max_length=100, null=True, unique=True, verbose_name='Client ID MQTT')),
                ('last_seen', models.DateTimeField(blank=True, help_text='Última vez que el dispositivo se conectó', null=True, verbose_name='Última Conexión')),
                ('connection_status', models.CharField(choices=[('online', 'En Línea'), ('offline', 'Fuera de Línea'), ('error', 'Error')], db_index=True, default='offline', max_length=20, verbose_name='Estado de Conexión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('operador_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Operador Asignado')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'db_table': 'dispositivos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispositivoSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuracion_json', models.JSONField(blank=True, default=dict, help_text='Configuración específica de este sensor en este dispositivo', verbose_name='Configuración JSON')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.dispositivo', verbose_name='Dispositivo')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.sensor', verbose_name='Sensor')),
            ],
            options={
                'verbose_name': 'Dispositivo-Sensor',
                'verbose_name_plural': 'Dispositivos-Sensores',
                'db_table': 'dispositivos_sensores',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='sensores',
            field=models.ManyToManyField(related_name='dispositivos', through='devices.DispositivoSensor', to='sensors.sensor', verbose_name='Sensores'),
        ),
        migrations.AddIndex(
            model_name='dispositivosensor',
            index=models.Index(fields=['dispositivo', 'sensor'], name='idx_disp_sensor'),
        ),
        migrations.AddIndex(
            model_name='dispositivosensor',
            index=models.Index(fields=['activo'], name='idx_disp_sensor_activo'),
        ),
        migrations.AlterUniqueTogether(
            name='dispositivosensor',
            unique_together={('dispositivo', 'sensor')},
        ),
        migrations.AddIndex(
            model_name='dispositivo',
            index=models.Index(fields=['estado'], name='idx_dispositivo_estado'),
        ),
        migrations.AddIndex(
            model_name='dispositivo',
            index=models.Index(fields=['operador_asignado'], name='idx_dispositivo_operador'),
        ),
        migrations.AddIndex(
            model_name='dispositivo',
            index=models.Index(fields=['mqtt_enabled'], name='idx_dispositivo_mqtt'),
        ),
        migrations.AddIndex(
            model_name='dispositivo',
            index=models.Index(fields=['connection_status'], name='idx_dispositivo_conn_status'),
        ),
        migrations.AddIndex(
            model_name='dispositivo',
            index=models.Index(fields=['-created_at'], name='idx_dispositivo_created'),
        ),
    ]
