# Generated by Django 5.0.1 on 2025-12-04 20:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre identificador de la configuración del broker', max_length=100, unique=True, verbose_name='Nombre')),
                ('host', models.CharField(help_text='Dirección del broker MQTT (ej: localhost, broker.emqx.io)', max_length=255, verbose_name='Host')),
                ('port', models.IntegerField(default=1883, help_text='Puerto del broker (1883 para MQTT, 8883 para MQTTS)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='Puerto')),
                ('protocol', models.CharField(choices=[('mqtt', 'MQTT'), ('mqtts', 'MQTT over TLS'), ('ws', 'WebSocket'), ('wss', 'WebSocket Secure')], default='mqtt', max_length=10, verbose_name='Protocolo')),
                ('username', models.CharField(blank=True, help_text='Usuario para autenticación en el broker', max_length=100, null=True, verbose_name='Usuario')),
                ('password', models.CharField(blank=True, help_text='Contraseña para autenticación (se recomienda encriptar)', max_length=255, null=True, verbose_name='Contraseña')),
                ('keepalive', models.IntegerField(default=60, help_text='Intervalo de keep-alive en segundos', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(3600)], verbose_name='Keep Alive (segundos)')),
                ('clean_session', models.BooleanField(default=True, help_text='Si es True, el broker no guardará el estado de la sesión', verbose_name='Sesión Limpia')),
                ('use_tls', models.BooleanField(default=False, help_text='Habilitar conexión segura con TLS/SSL', verbose_name='Usar TLS')),
                ('ca_cert', models.TextField(blank=True, help_text='Certificado de la autoridad certificadora (PEM format)', null=True, verbose_name='Certificado CA')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si esta configuración está activa', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Configuración de Broker',
                'verbose_name_plural': 'Configuraciones de Brokers',
                'db_table': 'mqtt_broker_config',
                'ordering': ['-is_active', 'nombre'],
                'indexes': [models.Index(fields=['is_active'], name='idx_broker_active')],
            },
        ),
        migrations.CreateModel(
            name='MQTTTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del topic', max_length=100, unique=True, verbose_name='Nombre')),
                ('topic_pattern', models.CharField(help_text='Patrón del topic MQTT. Ej: sensors/{device_id}/{sensor_type}', max_length=255, verbose_name='Patrón del Topic')),
                ('tipo', models.CharField(choices=[('publish', 'Publicación'), ('subscribe', 'Suscripción'), ('both', 'Ambos')], default='both', max_length=10, verbose_name='Tipo de Topic')),
                ('qos', models.IntegerField(choices=[(0, 'At most once (0)'), (1, 'At least once (1)'), (2, 'Exactly once (2)')], default=1, help_text='Quality of Service por defecto', verbose_name='QoS')),
                ('retain', models.BooleanField(default=False, help_text='El broker retendrá el último mensaje publicado', verbose_name='Retener Mensaje')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del propósito del topic', verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Topic MQTT',
                'verbose_name_plural': 'Topics MQTT',
                'db_table': 'mqtt_topics',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['tipo'], name='idx_mqtt_topic_tipo')],
            },
        ),
        migrations.CreateModel(
            name='MQTTCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, help_text='Identificador único del cliente MQTT', max_length=100, unique=True, verbose_name='Client ID')),
                ('username', models.CharField(help_text='Usuario para autenticación MQTT del dispositivo', max_length=100, verbose_name='Usuario MQTT')),
                ('password', models.CharField(help_text='Contraseña para autenticación MQTT (encriptada)', max_length=255, verbose_name='Contraseña MQTT')),
                ('use_device_cert', models.BooleanField(default=False, help_text='Indica si el dispositivo usa certificado para autenticación', verbose_name='Usar Certificado de Dispositivo')),
                ('client_cert', models.TextField(blank=True, help_text='Certificado del dispositivo (PEM format)', null=True, verbose_name='Certificado del Cliente')),
                ('client_key', models.TextField(blank=True, help_text='Clave privada del certificado (PEM format)', null=True, verbose_name='Clave Privada del Cliente')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('dispositivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mqtt_credential', to='devices.dispositivo', verbose_name='Dispositivo')),
            ],
            options={
                'verbose_name': 'Credencial MQTT',
                'verbose_name_plural': 'Credenciales MQTT',
                'db_table': 'mqtt_credentials',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client_id'], name='idx_mqtt_cred_client'), models.Index(fields=['is_active'], name='idx_mqtt_cred_active')],
            },
        ),
        migrations.CreateModel(
            name='DeviceMQTTConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_interval', models.IntegerField(default=60, help_text='Intervalo en segundos entre publicaciones', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(86400)], verbose_name='Intervalo de Publicación (segundos)')),
                ('qos', models.IntegerField(choices=[(0, 'At most once (0)'), (1, 'At least once (1)'), (2, 'Exactly once (2)')], default=1, help_text='Quality of Service para este dispositivo', verbose_name='QoS')),
                ('retain', models.BooleanField(default=False, help_text='Los mensajes del dispositivo serán retenidos por el broker', verbose_name='Retener Mensajes')),
                ('auto_reconnect', models.BooleanField(default=True, help_text='Reconectar automáticamente en caso de desconexión', verbose_name='Auto Reconexión')),
                ('last_connection', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de la última conexión exitosa', null=True, verbose_name='Última Conexión')),
                ('connection_status', models.CharField(choices=[('connected', 'Conectado'), ('disconnected', 'Desconectado'), ('error', 'Error')], db_index=True, default='disconnected', max_length=20, verbose_name='Estado de Conexión')),
                ('metadata_json', models.JSONField(blank=True, default=dict, help_text='Información adicional de configuración', verbose_name='Metadata JSON')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('broker', models.ForeignKey(help_text='Broker MQTT al que se conecta el dispositivo', on_delete=django.db.models.deletion.CASCADE, related_name='device_configs', to='mqtt.brokerconfig', verbose_name='Broker')),
                ('dispositivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mqtt_config', to='devices.dispositivo', verbose_name='Dispositivo')),
                ('publish_topic', models.ForeignKey(help_text='Topic principal para publicar datos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publishing_devices', to='mqtt.mqtttopic', verbose_name='Topic de Publicación')),
                ('subscribe_topics', models.ManyToManyField(blank=True, help_text='Topics a los que el dispositivo está suscrito', related_name='subscribing_devices', to='mqtt.mqtttopic', verbose_name='Topics de Suscripción')),
            ],
            options={
                'verbose_name': 'Configuración MQTT de Dispositivo',
                'verbose_name_plural': 'Configuraciones MQTT de Dispositivos',
                'db_table': 'mqtt_device_config',
                'ordering': ['-last_connection'],
                'indexes': [models.Index(fields=['connection_status'], name='idx_mqtt_dev_status'), models.Index(fields=['last_connection'], name='idx_mqtt_dev_last_conn'), models.Index(fields=['is_active'], name='idx_mqtt_dev_active')],
            },
        ),
    ]
