# Generated by Django 5.0.1 on 2025-12-05 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('mqtt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMQXUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, help_text='Nombre de usuario único para autenticación MQTT', max_length=255, unique=True, verbose_name='Usuario MQTT')),
                ('password_hash', models.CharField(help_text='Hash SHA256 de la contraseña (password_hash = SHA256(password + salt))', max_length=255, verbose_name='Hash de Contraseña')),
                ('salt', models.CharField(help_text='Salt aleatorio para el hash de contraseña', max_length=255, verbose_name='Salt')),
                ('is_superuser', models.BooleanField(db_index=True, default=False, help_text='Superusuario tiene acceso completo sin restricciones ACL', verbose_name='Es Superusuario MQTT')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('dispositivo', models.OneToOneField(blank=True, help_text='Dispositivo IoT asociado a este usuario MQTT (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emqx_user', to='devices.dispositivo', verbose_name='Dispositivo')),
            ],
            options={
                'verbose_name': 'Usuario EMQX',
                'verbose_name_plural': 'Usuarios EMQX',
                'db_table': 'mqtt_user',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='EMQXACL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, help_text='Nombre de usuario MQTT al que aplica esta regla', max_length=255, verbose_name='Usuario MQTT')),
                ('permission', models.CharField(choices=[('allow', 'Permitir'), ('deny', 'Denegar')], default='allow', help_text='Tipo de permiso: allow (permitir) o deny (denegar)', max_length=10, verbose_name='Permiso')),
                ('action', models.CharField(choices=[('publish', 'Publicar'), ('subscribe', 'Suscribir'), ('all', 'Todos')], help_text='Acción permitida/denegada: publish, subscribe o all', max_length=10, verbose_name='Acción')),
                ('topic', models.CharField(help_text='Patrón de topic MQTT. Soporta wildcards: + (un nivel), # (múltiples niveles)', max_length=255, verbose_name='Topic')),
                ('qos', models.SmallIntegerField(blank=True, choices=[(0, 'At most once (0)'), (1, 'At least once (1)'), (2, 'Exactly once (2)'), (None, 'Todos')], help_text='Quality of Service. NULL = todos los niveles', null=True, verbose_name='QoS')),
                ('retain', models.SmallIntegerField(blank=True, choices=[(0, 'No retener'), (1, 'Retener'), (None, 'Ambos')], help_text='Control de mensajes retenidos. 0=no, 1=sí, NULL=ambos', null=True, verbose_name='Retain')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('emqx_user', models.ForeignKey(blank=True, help_text='Usuario EMQX asociado (ayuda a mantener consistencia)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acl_rules', to='mqtt.emqxuser', verbose_name='Usuario EMQX')),
            ],
            options={
                'verbose_name': 'Regla ACL EMQX',
                'verbose_name_plural': 'Reglas ACL EMQX',
                'db_table': 'mqtt_acl',
                'ordering': ['username', 'topic'],
            },
        ),
        migrations.AddIndex(
            model_name='emqxuser',
            index=models.Index(fields=['username'], name='idx_mqtt_user_username'),
        ),
        migrations.AddIndex(
            model_name='emqxuser',
            index=models.Index(fields=['is_superuser'], name='idx_mqtt_user_superuser'),
        ),
        migrations.AddIndex(
            model_name='emqxacl',
            index=models.Index(fields=['username'], name='mqtt_acl_username_idx'),
        ),
        migrations.AddIndex(
            model_name='emqxacl',
            index=models.Index(fields=['username', 'topic'], name='idx_mqtt_acl_user_topic'),
        ),
        migrations.AddIndex(
            model_name='emqxacl',
            index=models.Index(fields=['action'], name='idx_mqtt_acl_action'),
        ),
    ]
